services:

  ebay-server:
    container_name: ebay-server
    build:
      context: .
      dockerfile: Dockerfile-store
    ports:
      - "8300:9991"
    environment:
      - STORE_NAME=ebay
    networks:
      - store_exercise_1

  amazon-server:
    container_name: amazon-server
    build:
      context: .
      dockerfile: Dockerfile-store
    ports:
      - "8301:9991"
    environment:
      - STORE_NAME=amazon
    networks:
      - store_exercise_1

  solution-server:
    container_name: solution-server
    build:
      context: ./
      dockerfile: ./solution/Dockerfile-solution
    ports:
      - "8302:9991"
    volumes:
      - ./:/app
#    environment:
#      - STORE_NAME=amazon
    networks:
      - store_exercise_1

  mysql_db:
    container_name: mysql_db_1
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: abcdef123
      MYSQL_DATABASE: app_db # Default database created at startup
      MYSQL_USER: dev
      MYSQL_PASSWORD: abcdef123
    volumes:
      - mysql_db_storage:/var/lib/mysql
    ports:
      - "33063:3306"
    networks:
      - store_exercise_1

  postgres_db:
    container_name: postgres_db
    image: postgres:15.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_storage:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.18
    restart: always
    ports:
      - "8090:9991"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - pgadmin:/var/lib/pgadmin


networks:
  store_exercise_1:
    driver: bridge


volumes:
  mysql_db_storage:
    driver: local
  postgres_db_storage:
    driver: local
  pgadmin:
    driver: local
