FROM python:3.10-slim

WORKDIR /app

COPY ./solution/requirements.txt /requirements.txt

RUN pip install -r /requirements.txt

COPY ./solution /app/solution

ENV PYTHONPATH=/app

CMD ["uvicorn", "solution.main:app", "--host", "0.0.0.0", "--port", "9991"]
